name: Test with pnpm

on:
  - push
  - pull_request

jobs:
  test:
    name: Test with pnpm
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.22.0, 12.x, 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup NodeJS ${{ matrix.node-version }}
      - name: Setup NodeJS 16
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          # node-version: ${{ matrix.node-version }}

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6

      - name: Install node dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test
